const database = [
  {
    name: "ШТАНЫ",
    catalogItemsList: [
      {
        id: 1,
        value: 4000,
        name: "ДЖИНСЫ",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany1.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 2,
        value: 4000,
        name: "ДЖИНСЫ",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany2.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 3,
        value: 2000,
        name: "ШОРТЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        priceBottom: " 2.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany3.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 4,
        value: 2000,
        name: "ВЕЛОСИПЕДКИ",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        priceBottom: " 2.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany4.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 5,
        value: 2000,
        name: "ЛОСИНЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        priceBottom: " 2.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany5.jpeg",
        category: 'ШТАНЫ'
      },
      {
        id: 6,
        value: 2000,
        name: "ЛОСИНЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        priceBottom: " 2.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany6.jpeg",
        category: 'ШТАНЫ'
      },
      {
        id: 7,
        value: 4000,
        name: "ДЖИНСЫ",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany7.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 8,
        value: 2000,
        name: "ШОРТЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        priceBottom: " 2.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany8.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 9,
        value: 2800,
        name: "СПОРТИВНЫЕ ШТАНЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.800KZT",
        priceBottom: " 3.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany9.jpeg",
        category: 'ШТАНЫ'
      },
      {
        id: 10,
        value: 4000,
        name: "ДЖИНСЫ",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany10.jpeg",
        category: 'ШТАНЫ'
      },
      {
        id: 11,
        value: 2200,
        name: "ТЁПЛЫЕ ЛОСИНЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.200KZT",
        priceBottom: " 2.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany11.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 12,
        value: 2800,
        name: "БРЮКИ",
        stock: "● В НАЛИЧИЙ",
        price: "2.800KZT",
        priceBottom: " 3.300KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany12.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 13,
        value: 2800,
        name: "БРЮКИ",
        stock: "● В НАЛИЧИЙ",
        price: "2.800KZT",
        priceBottom: " 3.300KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany13.jpeg",
        category: 'ШТАНЫ'
      },
      {
        id: 14,
        value: 2000,
        name: "ЛОСИНЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        priceBottom: " 2.400KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany14.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 15,
        value: 2500,
        name: "БРЮКИ",
        stock: "● В НАЛИЧИЙ",
        price: "2.500KZT",
        priceBottom: " 2.900KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес)",
        img: "/images/wtany/wtany15.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 16,
        value: 1800,
        name: "ЛОСИНЫ",
        stock: "● В НАЛИЧИЙ",
        price: "1.800KZT",
        priceBottom: " 2.400KZT",
        size: "Размеры: 74см(6-9.мес), 80см(9-12.мес), 86см(12-18.мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany16.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 17,
        value: 2800,
        name: "БРЮКИ",
        stock: "● В НАЛИЧИЙ",
        price: "2.800KZT",
        priceBottom: " 3.400KZT",
        size: "Размеры: 74см(6-9.мес), 80см(9-12.мес),  86см(12-18.мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany17.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 18,
        value: 2800,
        name: "БОКСЕРКИ",
        stock: "● В НАЛИЧИЙ",
        price: "2.800KZT",
        priceBottom: " 3.400KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес)",
        img: "/images/wtany/wtany18.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 19,
        value: 2800,
        name: "СПОРТИВНЫЕ ШТАНЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.800KZT",
        priceBottom: " 3.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany19.jpeg",
        category: "ШТАНЫ",
      },
      {
        id: 20,
        value: 2200,
        name: "ТЁПЛЫЕ ЛОСИНЫ",
        stock: "● В НАЛИЧИЙ",
        price: "2.200KZT",
        priceBottom: " 2.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        img: "/images/wtany/wtany20.jpeg",
        category: "ШТАНЫ",
      },
    ],
  },
  {
    name: "КОФТЫ",
    catalogItemsList: [
      {
        id: 21,
        name: "СВИТШОТ",
        stock: "● В НАЛИЧИЙ",
        price: "3.800KZT",
        img: "/images/koft/kofta1.jpeg",
        priceBottom: " 4.200KZT",
        size: "Размеры: 68см(3-6.мес), 74см(6-9.мес), 80см(12.мес), 86см(18.мес)",
        value: 3800,
        category: "КОФТЫ",
      },
      {
        id: 22,
        name: "СВИТШОТ",
        stock: "● В НАЛИЧИЙ",
        price: "3.800KZT",
        img: "/images/koft/kofta2.jpeg",
        priceBottom: " 4.200KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        value: 3800,
        category: "КОФТЫ",
      },
      {
        id: 23,
        name: "СВИТШОТ",
        stock: "● В НАЛИЧИЙ",
        price: "3.800KZT",
        img: "/images/koft/kofta3.jpeg",
        priceBottom: " 4.200KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        value: 3800,
        category: "КОФТЫ",
      },
      {
        id: 24,
        name: "СВИТШОТ",
        stock: "● В НАЛИЧИЙ",
        price: "3.800KZT",
        img: "/images/koft/kofta4.jpeg",
        priceBottom: " 4.200KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        value: 3800,
        category: "КОФТЫ",
      },
      {
        id: 25,
        name: "СВИТШОТ",
        stock: "● В НАЛИЧИЙ",
        price: "3.800KZT",
        img: "/images/koft/kofta5.jpeg",
        priceBottom: " 4.200KZT",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес),  80 см (9-12 мес), 86 см (12-18 мес)",
        value: 3800,
        category: "КОФТЫ",
      },
      {
        id: 26,
        name: "СВИТШОТ",
        stock: "● В НАЛИЧИЙ",
        price: "3.800KZT",
        img: "/images/koft/kofta6.jpeg",
        priceBottom: " 4.200KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        value: 3800,
        category: "КОФТЫ",
      },
      {
        id: 27,
        name: "МАЙКА",
        stock: "● В НАЛИЧИЙ",
        price: "1.500KZT",
        img: "/images/koft/kofta7.jpeg",
        priceBottom: " 2.000KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        value: 1500,
        category: "КОФТЫ",
      },
      {
        id: 28,
        name: "ФУТБОЛКА",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        img: "/images/koft/kofta8.jpeg",
        priceBottom: " 2.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        value: 2000,
        category: "КОФТЫ",
      },
      {
        id: 29,
        name: "КОФТА",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        img: "/images/koft/kofta9.jpeg",
        priceBottom: " 4.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        value: 4000,
        category: "КОФТЫ",
      },
      {
        id: 30,
        name: "КОФТА",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        img: "/images/koft/kofta10.jpeg",
        priceBottom: " 4.600KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        value: 4000,
        category: "КОФТЫ",
      },
      {
        id: 31,
        name: "ФУТБОЛКА",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        img: "/images/koft/kofta11.jpeg",
        priceBottom: " 2.600KZT",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес)",
        value: 2000,
        category: "КОФТЫ",
      },
      {
        id: 32,
        name: "ФУТБОЛКА",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        img: "/images/koft/kofta12.jpeg",
        priceBottom: " 2.600KZT",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес)",
        value: 2000,
        category: "КОФТЫ",
      },
      {
        id: 33,
        name: "ФУТБОЛКА",
        stock: "● В НАЛИЧИЙ",
        price: "2.000KZT",
        img: "/images/koft/kofta13.jpeg",
        priceBottom: " 2.400KZT",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        value: 2000,
        category: "КОФТЫ",
      },
    ],
  },
  {
    name: "НАБОРЫ",
    catalogItemsList: [
      {
        id: 34,
        value: 4200,
        name: "ДЛЯ НОВОРОЖДЕННЫХ",
        stock: "● В НАЛИЧИЙ",
        price: "4.200KZT ",
        img: "/images/nabor/nabor1.jpeg",
        priceBottom: " 4.800KZT",
        size: "Размеры: 56 см (0-3 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 35,
        value: 3700,
        name: "КОМПЛЕКТ 3в1",
        stock: "● В НАЛИЧИЙ",
        price: "3.700KZT",
        img: "/images/nabor/nabor2.jpeg",
        priceBottom: " 4.200KZT",
        size: "Размеры:68 см (3-6 мес), 74 см (6-9 мес), 86 см (12-18 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 36,
        value: 3000,
        name: "ДЛЯ НОВОРОЖДЕННЫХ",
        stock: "● В НАЛИЧИЙ",
        price: "3.000KZT",
        img: "/images/nabor/nabor3.jpeg",
        priceBottom: " 3.700KZT",
        size: "Размеры: 62 см (0-3 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 37,
        value: 3000,
        name: "ДЛЯ НОВОРОЖДЕННЫХ",
        stock: "● В НАЛИЧИЙ",
        price: "3.000KZT",
        img: "/images/nabor/nabor4.jpeg",
        priceBottom: " 3.700KZT",
        size: "Размеры: 62 см (0-3 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 38,
        value: 3000,
        name: "ДЛЯ НОВОРОЖДЕННЫХ",
        stock: "● В НАЛИЧИЙ",
        price: "3.000KZT",
        img: "/images/nabor/nabor5.jpeg",
        priceBottom: " 3.700KZT",
        size: "Размеры: 62 см (0-3 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 39,
        value: 3000,
        name: "ДЛЯ НОВОРОЖДЕННЫХ",
        stock: "● В НАЛИЧИЙ",
        price: "3.000KZT",
        img: "/images/nabor/nabor6.jpeg",
        priceBottom: " 3.700KZT",
        size: "Размеры: 62 см (0-3 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 40,
        value: 5000,
        name: "ДЛЯ НОВОРОЖДЕННЫХ",
        stock: "● В НАЛИЧИЙ",
        price: "5.000KZT",
        img: "/images/nabor/nabor7.jpeg",
        priceBottom: " 6.000KZT",
        size: "Размеры: 50-56 см (0-3 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 41,
        value: 4000,
        name: "ТРОЙКА ДЛЯ МАЛЬЧИКОВ",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        img: "/images/nabor/nabor8.jpeg",
        priceBottom: " 4.800KZT",
        size: "Размеры: 62 см (0-3 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 42,
        value: 4000,
        name: "НАБОР 3в1",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        img: "/images/nabor/nabor9.jpeg",
        priceBottom: " 4.600KZT",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес)",
        category: "НАБОРЫ",
      },
      {
        id: 43,
        value: 3800,
        name: "ЯРКИЙ НАБОР",
        stock: "● В НАЛИЧИЙ",
        price: "3.800KZT",
        img: "/images/nabor/nabor10.jpeg",
        priceBottom: " 4.200KZT",
        size: "Размеры: 68см(3-6.мес), 74см(6-9.мес), 80см(12.мес), 86см(18.мес)",
        category: "НАБОРЫ",
      },
      {
        id: 44,
        value: 4000,
        name: "ЯРКИЙ НАБОР",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        img: "/images/nabor/nabor11.jpeg",
        priceBottom: " 4.600KZT",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес)",
        category: "НАБОРЫ",
      },
    ],
  },
  {
    name: "МАТРАСЫ",
    catalogItemsList: [
      {
        id: 45,
        name: "МАТРАС",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        img: "/images/matr/matr1.jpeg",
        priceBottom: " 4.600KZT",
        size: "Размеры: S (0-12 мес)",
        value: 4000,
        category: "МАТРАСЫ",
      },
      {
        id: 46,
        name: "МАТРАС",
        stock: "● В НАЛИЧИЙ",
        price: "4.000KZT",
        img: "/images/matr/matr2.jpeg",
        priceBottom: " 4.600KZT",
        size: "Размеры: S (0-12 мес)",
        value: 4000,
        category: "МАТРАСЫ",
      },
    ],
  },
  {
    name: "ШАПКИ",
    catalogItemsList: [
      {
        id: 47,
        name: "МУСЛИНОВЫЕ ПЛЕНКИ",
        value: 1500,
        price: "1.500KZT",
        priceBottom: " 2.000KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/wapki/wap1.jpg",
        size: "В Наличий: 7 штук, в разных расцветках",
        category: "ШАПКИ",
      },
      {
        id: 48,
        name: "НОСКИ",
        value: 600,
        price: "600KZT",
        priceBottom: " 900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/wapki/wap2.jpeg",
        size: "Размеры: 0-6 мес",
        category: "ШАПКИ",
      },
      {
        id: 49,
        name: "УТЕПЛЁННЫЕ ШАПКИ",
        value: 1500,
        price: "1.500KZT",
        priceBottom: " 2.000KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/wapki/wap3.jpg",
        size: "",
        category: "ШАПКИ",
      },
      {
        id: 50,
        name: "ВЯЗАННЫЙ ПЛЕД",
        value: 5000,
        price: "5.000KZT",
        priceBottom: " 5.700KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/wapki/wap4.jpeg",
        size: "Есть в 3х расцветках",
        category: "ШАПКИ",
      },
      {
        id: 51,
        name: "ШАПКИ",
        value: 400,
        price: "400KZT",
        priceBottom: " 700KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/wapki/wap5.jpeg",
        size: "В наличий в разных расцетках",
        category: "ШАПКИ",
      },
      {
        id: 52,
        name: "ШАПКИ",
        value: 400,
        price: "400KZT",
        priceBottom: " 700KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/wapki/wap6.jpeg",
        size: "В наличий в разных расцетках",
        category: "ШАПКИ",
      },
      {
        id: 53,
        name: "МАХРОВЫЕ ПОЛОТЕНЦА",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 5.000KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/wapki/wap7.jpeg",
        size: "",
        category: "ШАПКИ",
      },
      {
        id: 54,
        name: "МАХРОВЫЕ ПОЛОТЕНЦА",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 5.000KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/wapki/wap8.jpeg",
        size: "",
        category: "ШАПКИ",
      },
    ],
  },
  {
    name: "СЛИПИКИ",
    catalogItemsList: [
      {
        id: 55,
        name: "CЛИПЫ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip1.jpeg",
        size: "Размеры: 56 см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 56,
        name: "CЛИПИКИ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip2.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 57,
        name: "КОМПЛЕКТ PRINCESS",
        value: 3000,
        price: "3.000KZT",
        priceBottom: " 3.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip3.jpeg",
        size: "Размеры: 56 см (0-2 мес), 62 см (0-3 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 58,
        name: "СЛИПИК",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.500KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip4.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 59,
        name: "СЛИПИК С ШАПОЧКОЙ",
        value: 4500,
        price: "4.500KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip5.jpeg",
        size: "Размеры: 62 см (0-3 мес)х2",
        category: "СЛИПИКИ",
      },
      {
        id: 60,
        name: "CЛИПЫ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip6.jpeg",
        size: "Размеры: 56 см (0-2 мес), 62 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 61,
        name: "СЛИПЫ",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip7.jpeg",
        size: "Размеры: 56 см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 62,
        name: "CЛИПИКИ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip8.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 63,
        name: "CЛИПЫ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip9.jpeg",
        size: "Размеры: 56 см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 64,
        name: "СЛИПИКИ С ШАПКОЙ",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip10.jpeg",
        size: "Размеры: 44 см (0-1 мес), 50 см (0-1 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 65,
        name: "СЛИПИКИ С ШАПКОЙ",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip11.jpeg",
        size: "Размеры: 44 см (0-1 мес), 50 см (0-1 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 66,
        name: "ЯРКИЕ СЛИПЫ",
        value: 3200,
        price: "3.200KZT",
        priceBottom: " 3.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip12.jpeg",
        size: "Размеры: 62 см (3 мес), 68 см (6 мес), 74 см (9 мес), 80 см (12 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 67,
        name: "ТЕПЛЫЕ СЛИПЫ",
        value: 5500,
        price: "5.500KZT",
        priceBottom: " 5.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip13.jpeg",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 68,
        name: "СЛИПЫ",
        value: 3200,
        price: "3.200KZT",
        priceBottom: " 3.800KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip14.jpeg",
        size: "Размеры: 68 см (6 мес), 74 см (9 мес), 80 см (12 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 69,
        name: "СЛИПИК С ШАПОЧКОЙ",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 3.990KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip15.jpeg",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес),  86 см (12-18 мес), 92 см (18-24 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 70,
        name: "СЛИПЫ",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip16.jpeg",
        size: "Размеры: 56 см (0-2 мес) 68 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 71,
        name: "КОМПЛЕКТ PRINCE",
        value: 3000,
        price: "3.000KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip17.jpeg",
        size: "Размеры: 62 см (0-3 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 72,
        name: "ЖЁЛТЫЕ СЛИПЫ",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip18.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 73,
        name: "СЛИПЫ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.100KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip19.jpeg",
        size: "Размеры: 56 см (0-2мес), 68 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 74,
        name: "БОДИКИ",
        value: 1900,
        price: "1.900KZT",
        priceBottom: " 2.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip20.jpeg",
        size: "Размеры: 56см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 75,
        name: "ТЕПЛЫЕ СЛИПЫ",
        value: 5500,
        price: "5.500KZT",
        priceBottom: " 6.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip21.jpeg",
        size: "Размеры: 56см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 76,
        name: "СЛИПЫ",
        value: 3200,
        price: "3.200KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip22.jpeg",
        size: "Размеры: 62 см (3 мес), 68 см (6 мес), 74 см (9 мес), 80 см (12 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 77,
        name: "СЛИПЫ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip23.jpeg",
        category: "СЛИПИКИ",
        size: "Размеры: Белый: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес) Зеленый: 62 см (0-3 мес), 74 см (6-9 мес) Розовый: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
      },
      {
        id: 78,
        name: "КОМПЛЕКТ ДЛЯ МАЛЫША",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip24.jpeg",
        size: "Размеры: 74 см (9 мес), 80 см (12 мес), 86 см (18 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 79,
        name: "СЛИПЫ",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.800KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip25.jpeg",
        size: "Размеры: 56 см (0-2 мес) 68 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 80,
        name: "БОДИКИ",
        value: 1900,
        price: "1.900KZT",
        priceBottom: " 2.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip26.jpeg",
        size: "Размеры: 56см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 81,
        name: "СЛИПЫ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip27.jpeg",
        size: "Размеры: Желтый: 56 см (0-2 мес), Красный: 56 см (0-2 мес), 68 см (3-6 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 82,
        name: "СЛИПИКИ С ШАПКОЙ",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip28.jpeg",
        size: "Размеры: 44 см (0-1 мес), 50 см (0-1 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 83,
        name: "СЛИПИКИ С ШАПКОЙ",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip29.jpeg",
        size: "Размеры: 44 см (0-1 мес), 50 см (0-1 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 84,
        name: "СЛИПИКИ С ШАПКОЙ",
        value: 4500,
        price: "4.500KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip30.jpeg",
        size: "Размеры: 56 см (0-3 мес) 62 см (3 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 85,
        name: "БОДИКИ",
        value: 1900,
        price: "1.900KZT",
        priceBottom: " 2.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip31.jpeg",
        size: "Размеры: 56см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "СЛИПИКИ",
      },
      {
        id: 86,
        name: "БОДИКИ",
        value: 1900,
        price: "1.900KZT",
        priceBottom: " 2.400KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/slip/slip14.jpeg",
        size: "Размеры: 56см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "СЛИПИКИ",
      },
    ],
  },
  {
    name: "КОМПЛЕКТЫ",
    catalogItemsList: [
      {
        id: 87,
        name: "СПОРТИВНЫЙ КОМБИНЕЗОН",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik1.jpeg",
        size: "Размеры: Размеры:62 см (3 мес), 68 см (6 мес), 74 см (9 мес), 80 см (12 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 88,
        name: "СПОРТИВНЫЙ КОМБИНЕЗОН",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik2.jpeg",
        size: "Размеры:62 см (3 мес), 68 см (6 мес), 74 см (9 мес),",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 89,
        name: "КОМБИНЕЗОН",
        value: 3900,
        price: "3.900KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik3.jpeg",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 90,
        name: "ФЛИСОВЫЙ КОМБИНЕЗОН",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik4.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 91,
        name: "КОМБИНЕЗОН",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.500KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik5.jpeg",
        size: "Размеры:68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 92,
        name: "КОМБИНЕЗОН",
        value: 5000,
        price: "5.000KZT",
        priceBottom: " 5.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik6.jpeg",
        size: "Размеры: 62 см (0-3 см), 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 93,
        name: "ФЛИСОВЫЙ КОМБИНЕЗОН",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik7.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 94,
        name: "КОМБИНЕЗОН",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.500KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik8.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 95,
        name: "КОМБИНЕЗОН",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik9.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 80 см (12 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 96,
        name: "КОМБИНЕЗОН",
        value: 7000,
        price: "7.000KZT",
        priceBottom: " 7.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik10.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес),80 см (9-12 мес))",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 97,
        name: "КОМБИНЕЗОН",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik11.jpeg",
        size: "Размеры: 56 см (0-2 мес), 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 98,
        name: "КОМБИНЕЗОН",
        value: 3000,
        price: "3.000KZT",
        priceBottom: " 3.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik12.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 99,
        name: "КОМБИНЕЗОН",
        value: 3300,
        price: "3.300KZT",
        priceBottom: " 3.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik13.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 100,
        name: "КОМБИНЕЗОН",
        value: 3300,
        price: "3.300KZT",
        priceBottom: " 3.800KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik14.jpeg",
        size: "Размеры: 68 см (3-6 мес), 80 см (12 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 101,
        name: "КОМБИНЕЗОН",
        value: 3300,
        price: "3.300KZT",
        priceBottom: " 3.800KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik15.jpeg",
        size: "Размеры: 68 см (3-6 мес), 80 см (12 мес)",
        category: "КОМПЛЕКТЫ",
      },
      {
        id: 102,
        name: "КОМБИНЕЗОН",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 3.990KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/komb/kombik16.jpeg",
        size: "Размеры: 62 см (0-3 мес), 68 см (3-6 мес), 74 см (6-9 мес)",
        category: "КОМПЛЕКТЫ",
      },
    ],
  },
  {
    name: "ПИЖАМЫ",
    catalogItemsList: [
      {
        id: 103,
        name: "ПИЖАМА",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/pijama/pijama1.jpeg",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        category: "ПИЖАМЫ",
      },
      {
        id: 104,
        name: "ПИЖАМА",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/pijama/pijama2.jpeg",
        category: "ПИЖАМЫ",
        size: "Размеры:68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес)",
      },
      {
        id: 105,
        name: "ПИЖАМА",
        value: 3500,
        price: "3.500KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/pijama/pijama3.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес)",
        category: "ПИЖАМЫ",
      },
    ],
  },
  {
    name: "ПЛАТЬЯ",
    catalogItemsList: [
      {
        id: 106,
        name: "ПЛАТЬЕ",
        value: 4500,
        price: "4.500KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/platbe/plat1.jpeg",
        size: "Размеры: 74см(6-9.мес),80см(9-12.мес)",
        category: "ПЛАТЬЯ",
      },
      {
        id: 107,
        name: "ПЛАТЬЕ",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/platbe/plat2.jpeg",
        size: "Размеры:74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 92 см (18-24 мес)",
        category: "ПЛАТЬЯ",
      },
      {
        id: 108,
        name: "ПЛАТЬЕ",
        value: 4500,
        price: "4.500KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/platbe/plat3.jpeg",
        size: "Размеры: 74см(6-9.мес),80см(9-12.мес)",
        category: "ПЛАТЬЯ",
      },
      {
        id: 109,
        name: "ПЛАТЬЕ",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/platbe/plat4.jpeg",
        size: "Размеры:68 см (6-9 мес), 74 см (9-12 мес),  80 см (12-18 мес), 86 см (18-24 мес)",
        category: "ПЛАТЬЯ",
      },
    ],
  },
  {
    name: "КОМБИНЕЗОНЫ",
    catalogItemsList: [
      {
        id: 110,
        name: "ДВОЕЧКИ",
        value: 4500,
        price: "4.500KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp1.jpeg",
        size: "Размеры: 74 см (6-9 мес), 86см (12-18 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 111,
        name: "КОМПЛЕКТ",
        value: 4200,
        price: "4.200KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp2.jpeg",
        size: "Размеры: 74 см (6-9 мес), 86 см (9-12 мес), 92 см (18-24 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 112,
        name: "КОМЛПЕКТ",
        value: 4200,
        price: "4.200KZT",
        priceBottom: " 4.700KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp3.jpeg",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 113,
        name: "ДВОЕЧКИ",
        value: 4500,
        price: "4.500KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp4.jpeg",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес), 96 см (24-36 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 114,
        name: "ДВОЙКА",
        value: 4200,
        price: "4.200KZT",
        priceBottom: " 4.700KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp5.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес), 86 см (12-18 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 115,
        name: "ДВОЙКА",
        value: 4400,
        price: "4.400KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp6.jpeg",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 116,
        name: "КОСТЮМ",
        value: 4200,
        price: "4.200KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp7.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес),86 см (12-18 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 117,
        name: "КОСТЮМ",
        value: 4200,
        price: "4.200KZT",
        priceBottom: " 4.900KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp8.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 118,
        name: "КОМПЛЕКТ",
        value: 3800,
        price: "3.800KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp9.jpeg",
        category: "КОМБИНЕЗОНЫ",
        size: "Размеры: 74 см (9 мес), 80 см (12 мес),86 см (18 мес)",
      },
      {
        id: 119,
        name: "КОМБИНЕЗОН",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp10.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес)",
        category: "КОМБИНЕЗОНЫ",
      },
      {
        id: 120,
        name: "ДВОЙКА",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        category: "КОМБИНЕЗОНЫ",
        img: "/images/kompl/komp11.jpeg",
        size: "Размеры: 74 см (9 мес), 80 см (12 мес)",
      },
      {
        id: 121,
        name: "ДВОЙКА",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        category: "КОМБИНЕЗОНЫ",
        img: "/images/kompl/komp12.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес)",
      },
      {
        id: 122,
        name: "ДВОЙКА",
        value: 5000,
        price: "5.000KZT",
        category: "КОМБИНЕЗОНЫ",
        priceBottom: " 5.600KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp13.jpeg",
        size: "Размеры: 2-3 годика",
      },
      {
        id: 123,
        name: "ДВОЙКА",
        value: 4200,
        price: "4.200KZT",
        priceBottom: " 4.800KZT",
        category: "КОМБИНЕЗОНЫ",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp14.jpeg",
        size: "Размеры:  68 см (3-6 мес), 74 см (6-9 мес)",
      },
      {
        id: 124,
        name: "ДВОЙКА",
        value: 4300,
        price: "4.300KZT",
        priceBottom: " 4.800KZT",
        category: "КОМБИНЕЗОНЫ",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp15.jpeg",
        size: "Размеры: 68 см (6 мес), 80 см (12 мес), 86 см (18 мес)",
      },
      {
        id: 125,
        name: "КОСТЮМ",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        category: "КОМБИНЕЗОНЫ",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp16.jpeg",
        size: "Размеры: 74 см (6-9 мес)",
      },
      {
        id: 126,
        name: "ДВОЙКА",
        value: 4300,
        price: "4.300KZT",
        priceBottom: " 4.800KZT",
        category: "КОМБИНЕЗОНЫ",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp17.jpeg",
        size: "Размеры: 68 см (6 мес), 74 см (9 мес), 80 см (12 мес),86 см (18 мес)",
      },
      {
        id: 127,
        name: "КОСТЮМ",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.200KZT",
        category: "КОМБИНЕЗОНЫ",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp18.jpeg",
        size: "Размеры: 74 см (6-9 мес)",
      },
      {
        id: 128,
        name: "ДВОЙКА",
        value: 4000,
        price: "4.000KZT",
        priceBottom: " 4.600KZT",
        stock: "● В НАЛИЧИЙ",
        category: "КОМБИНЕЗОНЫ",
        img: "/images/kompl/komp19.jpeg",
        size: "Размеры: 68 см (3-6 мес), 74 см (6-9 мес), 80 см (9-12 мес)",
      },
      {
        id: 129,
        name: "ДВОЙКА",
        value: 4200,
        price: "4.200KZT",
        priceBottom: " 4.800KZT",
        stock: "● В НАЛИЧИЙ",
        category: "КОМБИНЕЗОНЫ",
        img: "/images/kompl/komp20.jpeg",
        size: "Размеры: 74 см (6-9 мес), 80 см (9-12 мес), 86 см (12-18 мес)",
      },
      {
        id: 130,
        name: "ДВОЙКА",
        value: 3600,
        price: "3.600KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        category: "КОМБИНЕЗОНЫ",
        img: "/images/kompl/komp21.jpeg",
        size: "Размеры: 68 см (6-9 мес), 74 см (9-12 мес), 80 см (12-18 мес), 92 см (18-24 мес)",
      },
      {
        id: 131,
        name: "ЛЕТНЯЯ ДВОЙКА",
        value: 3800,
        price: "3.800KZT",
        category: "КОМБИНЕЗОНЫ",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp22.jpeg",
        size: "Размеры:  80 см (12 мес), 86 см (18 мес) 18-24",
      },
      {
        id: 132,
        name: "ДВОЙКА С ПЛАТЬЁМ",
        value: 3800,
        category: "КОМБИНЕЗОНЫ",
        price: "3.800KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp23.jpeg",
        size: "Размеры: 68 см (6-9 мес), 74 см (9-12мес), 80 см (12-18 мес), 86 см (18-24 мес)",
      },
      {
        id: 133,
        name: "ДВОЙКА",
        value: 3500,
        category: "КОМБИНЕЗОНЫ",
        price: "3.500KZT",
        priceBottom: " 4.200KZT",
        stock: "● В НАЛИЧИЙ",
        img: "/images/kompl/komp24.jpeg",
        size: "Размеры: 68 см (6-9 мес), 74 см (9-12 мес), 80 см (12-18 мес), 86 см (18-24 мес)",
      },
    ],
  },
];

export default database;
